version: "2"
services:
  webserver:
    environment:
      MOODLE_DOCKER_TRAEFIK: "${MOODLE_DOCKER_TRAEFIK}"
      MOODLE_DOCKER_TRAEFIK_HTTPS: "${MOODLE_DOCKER_TRAEFIK_HTTPS}"
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:${MOODLE_DOCKER_WEB_HOST}"
      - 'traefik.docker.network=traefik_default'
    networks:
      - default
      - pontsun
  exttests:
    networks:
      - default
      - pontsun
  selenium:
    networks:
      - default
      - pontsun

networks:
  default:
  pontsun:
    external:
      name: ${MOODLE_DOCKER_TRAEFIK_NETWORK}
